export const CONTACTS_DATA = [
  {
    id: 1,
    name: "Ronald Richards",
    role: "Owner",
    email: "alber@borer.com",
    createdAt: "Feb 5, 2021",
    profile: "",
  },
  {
    id: 2,
    name: "Jacob Jones",
    role: "Owner",
    email: "alber@borer.com",
    createdAt: "Feb 5, 2021",
    profile: "https://i.pravatar.cc/300",
  },
  {
    id: 3,
    name: "Ronald Richards",
    role: "Owner",
    email: "alber@borer.com",
    createdAt: "Feb 5, 2021",
    profile: "",
  },
  {
    id: 4,
    name: "Jacob Jones",
    role: "Owner",
    email: "alber@borer.com",
    createdAt: "Feb 5, 2021",
    profile: "https://i.pravatar.cc/300",
  },
  {
    id: 5,
    name: "Ronald Richards",
    role: "Owner",
    email: "alber@borer.com",
    createdAt: "Feb 5, 2021",
    profile: "",
  },
  {
    id: 6,
    name: "Ronald Richards",
    role: "Owner",
    email: "alber@borer.com",
    createdAt: "Feb 5, 2021",
    profile: "",
  },
  {
    id: 7,
    name: "Jacob Jones",
    role: "Owner",
    email: "alber@borer.com",
    createdAt: "Feb 5, 2021",
    profile: "https://i.pravatar.cc/300",
  },
  {
    id: 8,
    name: "Ronald Richards",
    role: "Owner",
    email: "alber@borer.com",
    createdAt: "Feb 5, 2021",
    profile: "",
  },
  {
    id: 9,
    name: "Jacob Jones",
    role: "Owner",
    email: "alber@borer.com",
    createdAt: "Feb 5, 2021",
    profile: "https://i.pravatar.cc/300",
  },
  {
    id: 10,
    name: "Ronald Richards",
    role: "Owner",
    email: "alber@borer.com",
    createdAt: "Feb 5, 2021",
    profile: "",
  },
];
